// Generate React icon components from the SVG files in src/assets/icons/.
//   npm run icons:generate   → (re)writes src/components/icons/index.tsx
//   npm run icons:check      → fails if the generated file is out of date (used by CI)
// Icons render currentColor so they inherit text colour, and take the usual SVG props.
import { promises as fs } from "node:fs";
import path from "node:path";

const SRC = path.join(process.cwd(), "src/assets/icons");
const OUT = path.join(process.cwd(), "src/components/icons/index.tsx");

const pascal = (s) =>
  s
    .replace(/\.svg$/i, "")
    .replace(/[^a-z0-9]+/gi, " ")
    .trim()
    .split(/\s+/)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");

// Strip the wrapper <svg> and keep its children + viewBox; force currentColor so icons inherit colour.
function body(svg) {
  const viewBox = (/viewBox="([^"]+)"/i.exec(svg) || [])[1] || "0 0 24 24";
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/i, "")
    .replace(/<\/svg>[\s\S]*$/i, "")
    .replace(/\s(width|height)="[^"]*"/gi, "")
    .replace(/(fill|stroke)="(?!none)[^"]*"/gi, '$1="currentColor"')
    .trim();
  return { viewBox, inner };
}

const files = (await fs.readdir(SRC).catch(() => []))
  .filter((f) => /\.svg$/i.test(f))
  .sort();
const parts = [];
for (const f of files) {
  const { viewBox, inner } = body(await fs.readFile(path.join(SRC, f), "utf8"));
  parts.push(
    "export function " +
      pascal(f) +
      "(props: React.SVGProps<SVGSVGElement>) {\n" +
      "  return (\n" +
      '    <svg viewBox="' +
      viewBox +
      '" xmlns="http://www.w3.org/2000/svg" aria-hidden {...props}>\n' +
      "      " +
      inner +
      "\n" +
      "    </svg>\n" +
      "  );\n" +
      "}",
  );
}
const out =
  "// GENERATED by scripts/generate-icons.mjs - do not edit. Add an SVG to src/assets/icons/,\n" +
  "// then run: npm run icons:generate\n" +
  'import type * as React from "react";\n\n' +
  parts.join("\n\n") +
  "\n" +
  (parts.length ? "" : "export {};\n");

if (process.argv.includes("--check")) {
  const cur = await fs.readFile(OUT, "utf8").catch(() => "");
  if (cur.trim() !== out.trim()) {
    console.error(
      "Icons are out of date - run: npm run icons:generate (then commit the result).",
    );
    process.exit(1);
  }
  console.log("Icons up to date.");
} else {
  await fs.mkdir(path.dirname(OUT), { recursive: true });
  await fs.writeFile(OUT, out, "utf8");
  console.log(
    "Wrote " +
      files.length +
      " icon(s) -> " +
      path.relative(process.cwd(), OUT),
  );
}
