// GENERATED by scripts/generate-icons.mjs - do not edit. Add an SVG to src/assets/icons/,
// then run: npm run icons:generate
import type * as React from "react";

export function IconBulletArrow(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox="0 0 4 4"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      {...props}
    >
      <path
        d="M0.5 2H3.5M2.25 0.75L3.5 2L2.25 3.25"
        stroke="currentColor"
        stroke-width="0.5"
        stroke-linecap="round"
        stroke-linejoin="round"
        fill="none"
      />
    </svg>
  );
}

export function IconChevron(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox="0 0 16 16"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      {...props}
    >
      <path
        d="M3.33333 8L8 3.33333L12.6667 8"
        stroke="currentColor"
        fill="none"
      />
    </svg>
  );
}

export function IconClose(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      {...props}
    >
      <path
        d="M6 6L18 18"
        stroke="currentColor"
        stroke-width="1.6"
        fill="none"
      />
      <path
        d="M18 6L6 18"
        stroke="currentColor"
        stroke-width="1.6"
        fill="none"
      />
    </svg>
  );
}

export function IconLinkedin(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox="0 0 17 16"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      {...props}
    >
      <path
        d="M13.7688 13.6331H11.3745V9.92034C11.3745 9.035 11.3585 7.89529 10.1292 7.89529C8.88209 7.89529 8.69128 8.85991 8.69128 9.85588V13.6328H6.29691V5.99793H8.5955V7.04132H8.62768C8.85772 6.65188 9.19012 6.33151 9.5895 6.11433C9.98887 5.89714 10.4403 5.79129 10.8956 5.80802C13.3224 5.80802 13.7698 7.38854 13.7698 9.4447L13.7688 13.6331ZM3.59528 4.95429C3.32047 4.95434 3.0518 4.8737 2.82328 4.72257C2.59475 4.57143 2.41663 4.35659 2.31142 4.10522C2.20621 3.85384 2.17864 3.57722 2.2322 3.31034C2.28577 3.04345 2.41806 2.79828 2.61235 2.60584C2.80664 2.4134 3.05419 2.28232 3.32372 2.22919C3.59324 2.17606 3.87262 2.20325 4.12653 2.30734C4.38044 2.41142 4.59748 2.58772 4.7502 2.81394C4.90292 3.04016 4.98446 3.30615 4.98451 3.57825C4.98454 3.75892 4.94863 3.93783 4.87883 4.10476C4.80904 4.2717 4.70672 4.42338 4.57772 4.55116C4.44872 4.67893 4.29555 4.7803 4.12699 4.84947C3.95842 4.91864 3.77775 4.95426 3.59528 4.95429ZM4.79246 13.6331H2.3956V5.99793H4.79246V13.6331ZM14.9625 0.00109011H1.19244C0.879902 -0.00240219 0.578731 0.117109 0.355136 0.333362C0.131541 0.549614 0.0038144 0.844915 0 1.15438V14.8454C0.00368385 15.155 0.131336 15.4505 0.354923 15.667C0.57851 15.8835 0.879747 16.0032 1.19244 15.9999H14.9625C15.2758 16.0038 15.5779 15.8844 15.8024 15.6679C16.0268 15.4515 16.1554 15.1556 16.1597 14.8454V1.15339C16.1552 0.843314 16.0266 0.547677 15.8021 0.331429C15.5777 0.115182 15.2757 -0.00398762 14.9625 0.000101881"
        fill="currentColor"
      />
    </svg>
  );
}

export function IconX(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox="0 0 18 16"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      {...props}
    >
      <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M13.9027 0H16.6541L10.6435 6.87L17.715 16H12.1782L7.84196 10.3313L2.88024 16H0.127266L6.55617 8.65125L0 0H5.67717L9.59674 5.18109L13.9027 0ZM12.937 14.3531H14.4618L4.85005 1.56039H3.21379L12.937 14.3531Z"
        fill="currentColor"
      />
    </svg>
  );
}

export function IconYoutube(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox="0 0 23 16"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      {...props}
    >
      <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M4 0H19C21.2091 0 23 1.79086 23 4V12C23 14.2091 21.2091 16 19 16H4C1.79086 16 0 14.2091 0 12V4C0 1.79086 1.79086 0 4 0ZM9 4.5V11.5L15.5 8L9 4.5Z"
        fill="currentColor"
      />
    </svg>
  );
}
